/* src/tfconfig.h.  Generated by configure.  */
/*************************************************************************
 *  TinyFugue - programmable mud client
 *  Copyright (C) 1999, 2002, 2003, 2004, 2005, 2006-2007 Ken Keys
 *
 *  TinyFugue (aka "tf") is protected under the terms of the GNU
 *  General Public License.  See the file "COPYING" for details.
 ************************************************************************/
/* $Id: tfconfig.h.in,v 35004.36 2007/01/13 23:12:39 kkeys Exp $ */

/* This file must not have trailing carriage returns on lines:  they will
 * confuse configure.  (With autoconf 2.13, a trailing space and comment
 * on these lines let them work as intended.  But in 2.59, the trailing
 * comment causes problems too.)
 */

#define PLATFORM_UNIX 1

#define MAILDIR "/usr/spool/mail"
#define RETSIGTYPE void
/* #undef pid_t */
/* #undef size_t */
/* #undef time_t */
/* #undef socklen_t */

#define HAVE_UNISTD_H 1
#define HAVE_SYS_WAIT_H 1
#define STDC_HEADERS 1
#define HAVE_MEMORY_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_LOCALE_H 1
#define NETINET_IN_H <netinet/in.h>
#define ARPA_INET_H <arpa/inet.h>
#define NETDB_H <netdb.h>
#define HAVE_PWD_H 1
#define NEED_PTEM_H 0
#define HAVE_ZLIB_H 1
#define HAVE_LIBZ 1
#define SOCKS 0
#define HAVE_SSL 1

#define HAVE_BCOPY 1
#define HAVE_BZERO 1
#define HAVE_CONNECT 1
#define HAVE_FILENO 1
#define HAVE_GETCWD 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETHOSTNAME 1
#define HAVE_GETIPNODEBYNAME 0
#define HAVE_GETPWNAM 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GETWD 1
#define HAVE_H_ERRNO 0
#define HAVE_HSTRERROR 1
#define HAVE_INDEX 1
#define HAVE_INET_ATON 1
#define HAVE_INET_PTON 0
#define HAVE_KILL 1
#define HAVE_MEMCPY 1
#define HAVE_MEMSET 1
#define HAVE_RAISE 1
#define HAVE_SETLOCALE 1
#define HAVE_SETRLIMIT 1
#define HAVE_SIGACTION 1
#define HAVE_SRAND 1
#define HAVE_SRANDOM 1
#define HAVE_STRCASECMP 1
#define HAVE_STRCHR 1
#define HAVE_STRCMPI 0
#define HAVE_STRCSPN 1
#define HAVE_STRERROR 1
#define HAVE_STRFTIME 1
#define HAVE_STRICMP 0
#define HAVE_STRTOD 1
#define HAVE_TZSET 1
#define HAVE_WAITPID 1

#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8

#define TERMCAP 1
#define HARDCODE 0
#define HAVE_TERMIOS_H 1
#define HAVE_TERMIO_H 0
#define HAVE_SGTTY_H 0

#define HAVE_SOCKADDR_SA_LEN 0
#define HAVE_GETADDRINFO 1
#define HAVE_GAI_STRERROR 1
#define ENABLE_INET6 1
#define DISABLE_CORE 1
#define IN6_ADDR in6_addr
#define NO_HISTORY 0
#define NO_PROCESS 0
#define NO_FLOAT 0
#define NCOLORS 256

#define HAVE_MCCP (HAVE_ZLIB_H && HAVE_LIBZ)

#define inline __inline__

#include "tfdefs.h"

#define NDEBUG 1
#include <assert.h>

